
export const data = [
    {
        _id: 1,
        type: { id: 1, name: "meat" },
        name: 'Fleto2',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 2,
        type: { id: 1, name: "meat" },
        name: 'Fleto11111',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 3,
        type: { id: 1, name: "meat" },
        name: 'Fleto1111',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        starذs: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 4,
        type: { id: 1, name: "meat" },
        name: 'Fleto111',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 5,
        type: { id: 1, name: "meat" },
        name: 'Fleto11',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 6,
        type: { id: 1, name: "meat" },
        name: 'Fleto1',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    }, {
        _id: 7,
        type: { id: 1, name: "meat" },
        name: 'Fleto0000',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 8,
        type: { id: 1, name: "meat" },
        name: 'Fleto000',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 9,
        type: { id: 1, name: "meat" },
        name: 'Fleto00',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 10,
        type: { id: 1, name: "meat" },
        name: 'Fleto0',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 11,
        type: { id: 1, name: "meat" },
        name: 'Fleto3',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 12,
        type: { id: 1, name: "meat" },
        name: 'Fleto33',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    }, {
        _id: 13,
        type: { id: 1, name: "meat" },
        name: 'Fleto3y3',
        image: <img className="image" className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 14,
        type: { id: 1, name: "meat" },
        name: 'Fleto333',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 15,
        type: { id: 1, name: "meat" },
        name: 'Fleto44',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 16,
        type: { id: 1, name: "meat" },
        name: 'Fleto4',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 17,
        type: { id: 1, name: "meat" },
        name: 'Fleto444',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 18,
        type: { id: 1, name: "meat" },
        name: 'Fleto55',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 20,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 19,
        type: { id: 1, name: "fish" },
        name: 'tona',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 18,
        type: { id: 1, name: "fish" },
        name: 'salamon',
        image: <img className="image" src={require("./images/meat.jpg").default} />,
        reviewNumber: 10,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
]

export const getProducts = () => {
    return data.map(d => d)
}

export const getProduct = (id) => {
    return data.map(d => d._id === id)
}

export const deleteProduct = (id) => {
    return data.filter(d => d._id !== id)
}