
export const data = [
    {
        _id: 1,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 2,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 3,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        starذs: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 4,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 5,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 6,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    }, {
        _id: 7,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 8,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 9,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 10,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 11,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 12,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    }, {
        _id: 13,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 14,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 15,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 16,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 17,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
    {
        _id: 18,
        type: 'Meet',
        name: 'Fleto',
        image: <img src={require("./images/meat.jpg").default} />,
        reviewNumber: 30,
        stars: 4,
        countInStock: 20,
        price: 100,
    },
]